version: "3.8" # Use the latest version of Docker Compose

services:
  be_rich_db:
    container_name: be_rich_db
    image: postgres:15.14 # Use the latest PostgreSQL image
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # Replace with your database name
      POSTGRES_USER: ${POSTGRES_USER} # Replace with your username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Replace with your password
    ports:
      - "5432:5432" # Expose port 5432 on the host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    init: true
    networks:
      - be_rich_network
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  be_rich_api:
    container_name: be_rich_api
    build:
      context: .
      dockerfile: Dockerfile.dev # Replace with your API application Dockerfile
    environment:
      DB_URL: ${DB_URL} # Ensure the API knows the DB URL
    ports:
      - "8000:8000" # Expose port 8000 on the host
    volumes:
      - .:/app # Mount current directory to /app in container for live reload
      - /app/__pycache__ # Exclude __pycache__ from volume mount
      - /app/.pytest_cache # Exclude pytest cache from volume mount
    depends_on:
      be_rich_db:
        condition: service_healthy # Wait for the DB to be healthy
    restart: unless-stopped
    init: true
    networks:
      - be_rich_network

networks:
  be_rich_network:
    driver: bridge # Use bridge network driver
volumes:
  postgres_data: # Named volume to persist PostgreSQL data
