"""update entry model

Revision ID: 25a9537f417f
Revises: b3e660e225f1
Create Date: 2026-03-14 18:30:17.873947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a9537f417f'
down_revision: Union[str, None] = 'b3e660e225f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'payment_method',
               existing_type=postgresql.ENUM('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'),
               nullable=True)
    op.alter_column('entry', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entry', 'category',
               existing_type=postgresql.ENUM('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'category',
               existing_type=postgresql.ENUM('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'),
               nullable=False)
    op.alter_column('entry', 'installments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entry', 'payment_method',
               existing_type=postgresql.ENUM('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'),
               nullable=False)
    # ### end Alembic commands ###
