"""Separate income and expense and fixed

Revision ID: ac83cd0b24a9
Revises: b3e660e225f1
Create Date: 2026-03-20 00:16:35.348502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ac83cd0b24a9'
down_revision: Union[str, None] = 'b3e660e225f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomefixed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fixedexpenseentry')
    op.drop_table('entry')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('entry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_type', postgresql.ENUM('INCOME', 'EXPENSE', name='entrytype'), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'), autoincrement=False, nullable=False),
    sa.Column('installments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.ENUM('MARCELO', 'MARILIA', 'OTHER', name='source'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='entry_pkey')
    )
    op.create_table('fixedexpenseentry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.ENUM('MARCELO', 'MARILIA', 'OTHER', name='source'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fixedexpenseentry_pkey')
    )
    op.drop_table('incomefixed')
    op.drop_table('income')
    # ### end Alembic commands ###
