"""separate income and expense and fixed

Revision ID: af8b6fa7f6e1
Revises: b3e660e225f1
Create Date: 2026-03-20 00:27:15.059226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af8b6fa7f6e1'
down_revision: Union[str, None] = 'b3e660e225f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expensefixed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomefixed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('incomefixed')
    op.drop_table('income')
    op.drop_table('expensefixed')
    op.drop_table('expense')
    # ### end Alembic commands ###
