"""Initial migration

Revision ID: b3e660e225f1
Revises: 
Create Date: 2025-08-30 18:29:00.167587

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3e660e225f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.Enum('INCOME', 'EXPENSE', name='entrytype'), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.Enum('NU', 'PORTO', 'SANTANDER', 'PIX', name='paymentmethod'), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('APPS', 'HOUSE', 'GAS', 'INTERNET', 'ENERGY', 'HOUSE_INSTALLMENT', 'CAR', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'SUPERMARKET', 'CLOTHES', 'PHARMACY', 'PHONE', 'RENT', 'GIFT', 'OTHER', 'KIDS', name='category'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('entry')
    # ### end Alembic commands ###
