"""Added description field

Revision ID: fc1f25952d11
Revises: 480affe65a1c
Create Date: 2024-12-25 13:10:50.248608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc1f25952d11'
down_revision: Union[str, None] = '480affe65a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('NU', 'PORTO', 'PIX', name='paymentmethod'), nullable=False),
    sa.Column('category', sa.Enum('APPS', 'BILLS', 'CAR_REVIEW', 'CAR_TAX', 'CONECTCAR', 'EDUCATION', 'ENTERTAINMENT', 'FUEL', 'HEALTH', 'MARKET', 'PHARMACY', 'PHONE', 'OTHER', 'RENT', 'SHOPPING', name='category'), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_owner', sa.Enum('MARCELO', 'MARILIA', name='cardowner'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MARCELO', 'MARILIA', 'OTHER', name='incomesource'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('income')
    op.drop_table('expense')
    # ### end Alembic commands ###
